# Generated by Django 4.0.4 on 2022-09-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_rename_product_img_producto_product_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_description',
            field=models.TextField(max_length=20),
        ),
    ]
