# Generated by Django 4.0.4 on 2022-09-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0005_alter_producto_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='about',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_description',
            field=models.CharField(max_length=20),
        ),
    ]
