# Generated by Django 4.0.4 on 2022-09-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0006_producto_about_alter_producto_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_description',
            field=models.CharField(max_length=200),
        ),
    ]
