# Generated by Django 4.0.4 on 2022-09-29 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0008_producto_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='video',
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='products_videos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_api.producto')),
            ],
        ),
    ]
