# Generated by Django 4.0.4 on 2022-09-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0009_remove_producto_video_productvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
