# Generated by Django 4.0.4 on 2022-10-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0010_alter_productvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductVideo',
        ),
    ]
