# Generated by Django 4.0.4 on 2022-10-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_img_userprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
    ]
