# Generated by Django 4.0.4 on 2022-10-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_last_name_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
