# Generated by Django 4.0.4 on 2022-09-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_api', '0002_listapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
