# Generated by Django 4.0.4 on 2022-09-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_api', '0003_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapedido',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_pedido', to='pedido_api.pedido'),
        ),
    ]
