# Generated by Django 4.0.4 on 2022-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_api', '0004_alter_listapedido_id_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapedido',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
